customCommands:
  - key: "C"
    command: |
      git commit -m "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}: {{ .Form.Description }}" \
      {{- if .Form.LongDescription }}
      -m "{{ .Form.LongDescription }}" \
      {{- end }}
      {{- if .Form.BreakingChange }}
      -m "BREAKING CHANGE: {{ .Form.BreakingChange }}"
      {{- end }}
    description: "commit with commitizen"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat:üé∏ "
          - name: "Fix"
            description: "a bug fix"
            value: "fix:üêõ "
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs:‚úèÔ∏è "
          - name: "Styles"
            description: "Markup, white-space, formatting, missing semi-colons..."
            value: "style:üíÑ "
          - name: "Code Refactoring"
            description: "A code change that neither fixes a bug or adds a feature"
            value: "refactor:üí° "
          - name: "Performance Improvements"
            description: "A code change that improves performance"
            value: "perf:‚ö°Ô∏è "
          - name: "Tests"
            description: "Adding missing tests or correcting existing tests"
            value: "test:üíç "
          - name: "Builds"
            description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
            value: "build: "
          - name: "Release"
            description: "Create a release commit"
            value: "release:üíç "
          - name: "Continuous Integration"
            description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
            value: "ci:üé° "
          - name: "Chores"
            description: "Other changes that don't modify src or test files"
            value: "chore:ü§ñ "
          - name: "Reverts"
            description: "Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Enter the scope(s) of this change."
        key: "Scopes"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "input"
        title: "Enter a more detailed description (optional)."
        key: "LongDescription"
      - type: "input"
        title: "Describe the breaking change, if any (leave empty if none)."
        key: "BreakingChange"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: |
          {{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{ .Form.Description }}
          {{- if .Form.LongDescription }}

          :{{ .Form.LongDescription }}
          {{- end }}
          {{- if .Form.BreakingChange }}

          BREAKING CHANGE: {{ .Form.BreakingChange }}
          {{- end }}
